channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=23.0.1
- pip:
  - mlflow
  - cffi==1.15.1
  - cloudpickle==2.0.0
  - graphviz==0.17
  - lightgbm==3.3.4
  - matplotlib==3.4.3
  - psutil==5.8.0
  - scikit-learn==0.24.1
name: mlflow-env
