name: advanced_feature_engineer
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - scikit-learn=0.24.1
  - pip:
      - mlflow==1.28.1
      - wandb == 0.13.2
      - lightgbm==3.3.4
